default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  # username: <%= ENV['DATABASE_USER'] %>
  # password: <%= ENV['DATABASE_PASS'] %>
  host: CONKT_test
  port: 5432

development:
  <<: *default
  database: CONKT_test

test:
  <<: *default
  database: CONKT_test

production:
  <<: *default
  # database: CONKT_production
  # username: CONKT
  # password: <%= ENV['CONKT_DATABASE_PASSWORD'] %>
